title: Default Dashboard
proxmox:
  host: 192.168.1.100
  user: myuser
  pass: mypass
  node: mynode
docker:
  host: 192.168.1.100
  user: myuser
custom:
  custom1:
    host: 192.168.1.100
    user: myuser
    pass: mypass
    comand: mycommad
  custom2:
    host: 192.168.1.100
    user: myuser
    pass: mypass
    comand: mycommand

widgets:
  monitor:
    myproxmoxservice:
      service: proxmox
      type: lxc
      id: 100
      url: http://192.168.1.100:8080
    mydockerservice:
      service: docker
      name: mycontainer
      url: http://192.168.1.100:8080
    mycustomservice:
      service: custom1
      url: http://192.168.1.100:8080